# Generated by Django 6.0.3 on 2026-03-21 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treinadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField()),
                ('pokemon_name', models.CharField(max_length=100)),
                ('pokemon_tipo', models.CharField(max_length=50)),
                ('pokemon_imagem_url', models.URLField(blank=True, null=True)),
                ('data_captura', models.DateTimeField(auto_now_add=True)),
                ('anotacoes', models.TextField(blank=True, null=True)),
                ('treinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party', to='treinadores.treinador')),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'db_table': 'party',
                'ordering': ['pokemon_name'],
            },
        ),
    ]
