# Generated by Django 6.0.3 on 2026-03-21 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'Party', 'verbose_name_plural': 'Parties'},
        ),
    ]
